########### spring ###########
spring:
  application:
    name: hack-resource-core-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:hackdb
    username: sa
    password: hack
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

########### springdoc ###########
springdoc:
  swagger-ui:
    url: /v3/api-docs
    oauth2RedirectUrl: /swagger-ui/oauth2-redirect.html
    configUrl: /v3/api-docs/swagger-config
  server:
    url: http://127.0.0.1:40001

########### Server ###########
server:
  port: 40001
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - 'metrics'
          - 'prometheus'
          - 'health'
          - 'configprops'
          - 'configprops-prefix'
          - 'env'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      product: ${spring.application.name}

